/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package main;

import javax.swing.*;
import java.awt.*;
import UI.BookManagerPanel;
import UI.ReaderManagerPanel;
import UI.BorrowingManagerPanel;
import UI.StaffManagerPanel;
import UI.CategoryManagerPanel;
import UI.PublisherManagerPanel;
import UI.AuthorManagerPanel;
import UI.StatisticsPanel;

/**
 *
 * @author ACER
 */
public class NewCustomizer extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer NewCustomizer
     */
    public NewCustomizer() {
        initComponents();
        setupTabbedPane();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    private void setupTabbedPane() {
        setLayout(new BorderLayout());
        JTabbedPane tabbedPane = new JTabbedPane();

        tabbedPane.addTab("Quản lý Sách", new BookManagerPanel());
        tabbedPane.addTab("Quản lý Độc giả", new ReaderManagerPanel());
        tabbedPane.addTab("Quản lý Mượn/Trả", new BorrowingManagerPanel());
        tabbedPane.addTab("Quản lý Nhân viên", new StaffManagerPanel());
        tabbedPane.addTab("Quản lý Danh mục", new CategoryManagerPanel());
        tabbedPane.addTab("Quản lý Nhà xuất bản", new PublisherManagerPanel());
        tabbedPane.addTab("Quản lý Tác giả", new AuthorManagerPanel());
        tabbedPane.addTab("Thống kê/Báo cáo", new StatisticsPanel());

        add(tabbedPane, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        // Để trống vì đã custom lại layout ở setupTabbedPane
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Quản lý Thư viện");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(1000, 700);
            frame.setLocationRelativeTo(null);
            frame.setContentPane(new NewCustomizer());
            frame.setVisible(true);
        });
    }
}
